### ISSUE TITLE
Duda información progenitores

### ISSUE THREAD

**Issue by jcballesteros** [opencitydata/sector-publico-territorio#25]
En los ejemplos de territorio (http://vocab.linkeddata.es/datosabiertos/def/sector-publico/territorio/index-en.html) según vamos bajando de entidad los descendientes conocen la información de los progenitores.

País (no tiene progenitores)

Autonomia (tiene País)

Provincia (tiene País y Autonomía)

Municipio (tiene País, Autonomía y Provincia)

Distrito  (tiene País, Autonomía, Provincia y Municipio)

Sin embargo cuando llegamos a Sección Censal y Barrio, esto cambia:

Barrio (tiene Municipio)

Seccion Censal (tiene Municipio y Distrito).

¿Esto es así? O ¿en Distrito y Seccion Censal debería existir tambien la información de todos los progenitores?

**Comment by ocorcho** [comment]
Efectivamente, no hay nada que impida que también tengan referencias a las unidades administrativas más generales. @paoespinozarias puede incluir estas referencias en los ejemplos, y actualizar la documentación
